"""empty message

Revision ID: 3e08443efd0
Revises: d9deaa7395
Create Date: 2016-11-21 14:46:52.731048

"""

# revision identifiers, used by Alembic.
revision = '3e08443efd0'
down_revision = 'd9deaa7395'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorys', 'count')
    op.create_unique_constraint(None, 'categorys', ['tag'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorys')
    op.add_column('categorys', sa.Column('count', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
